[build]
builder = "nixpacks"
buildCommand = "npm run build"

# Las variables de entorno deben estar disponibles durante el build
[build.env]
NODE_ENV = "production"
NEXTAUTH_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXTAUTH_SECRET = "${RAILWAY_SECRET_NEXTAUTH_SECRET}"
DATABASE_URL = "${RAILWAY_DATABASE_URL}"
DIRECT_URL = "${RAILWAY_DIRECT_URL}"
NEXT_PUBLIC_APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXT_PUBLIC_API_URL = "https://${RAILWAY_PUBLIC_DOMAIN}/api"
JWT_SECRET = "${RAILWAY_SECRET_JWT_SECRET}"

# Variables de entorno para el despliegue
[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numRetries = 10

# Variables de entorno para el despliegue
[deploy.env]
NODE_ENV = "production"
NEXTAUTH_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXTAUTH_SECRET = "${RAILWAY_SECRET_NEXTAUTH_SECRET}"
DATABASE_URL = "${RAILWAY_DATABASE_URL}"
DIRECT_URL = "${RAILWAY_DIRECT_URL}"
NEXT_PUBLIC_APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXT_PUBLIC_API_URL = "https://${RAILWAY_PUBLIC_DOMAIN}/api"
JWT_SECRET = "${RAILWAY_SECRET_JWT_SECRET}" 