[build]
builder = "nixpacks"
buildCommand = "npm install && npm install recharts && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production" 