[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numRetries = 10

[deploy.env]
NODE_ENV = "production"
NEXTAUTH_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
# NEXTAUTH_SECRET debe ser configurado manualmente en Railway
# DATABASE_URL = "${RAILWAY_DATABASE_URL}"
# DIRECT_URL = "${RAILWAY_DIRECT_URL}" 