[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
NEXTAUTH_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXTAUTH_SECRET = "${RAILWAY_SECRET_NEXTAUTH_SECRET}"
DATABASE_URL = "${RAILWAY_DATABASE_URL}"
DIRECT_URL = "${RAILWAY_DIRECT_URL}" 